export const styles: Record<string, React.CSSProperties> = {
  nav: { position: "fixed", top: 0, left: 0, right: 0, zIndex: 200, background: "rgba(255,255,255,0.92)", backdropFilter: "blur(24px)", borderBottom: "1px solid var(--border)", padding: "0 48px", height: 64, display: "flex", alignItems: "center", justifyContent: "space-between" },
  wordmark: { fontFamily: "Syne, sans-serif", fontSize: 17, fontWeight: 800, letterSpacing: "-0.02em", color: "var(--text)" },
  wordmarkEm: { color: "var(--pink)" },
  btnGhost: { fontSize: 13, fontWeight: 600, color: "var(--pink)", background: "var(--pinkbg)", border: "1px solid var(--pinkbr)", borderRadius: 9, padding: "9px 18px", textDecoration: "none", display: "inline-block" },
  section: { maxWidth: 1140, margin: "0 auto", padding: "80px 48px" },
  sectionTitle: { fontFamily: "Syne, sans-serif", fontSize: 22, fontWeight: 700, letterSpacing: "-0.02em" },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))", gap: 16 },
  card: { background: "#fff", border: "1px solid var(--border)", borderRadius: 18, padding: 26, cursor: "pointer", transition: "all 0.2s", overflow: "hidden" as const },
  cardImg: { width: "calc(100% + 52px)", margin: "-26px -26px 16px -26px", height: 160, objectFit: "cover" as const, display: "block" },
  catTag: { fontSize: 11, fontWeight: 700, letterSpacing: "0.05em", textTransform: "uppercase" as const, color: "var(--pink)", background: "var(--pinkbg)", border: "1px solid var(--pinkbr)", padding: "3px 10px", borderRadius: 6 },
  overlay: { display: "flex", position: "fixed", inset: 0, zIndex: 300, background: "rgba(0,0,0,0.5)", backdropFilter: "blur(12px)", alignItems: "center", justifyContent: "center", padding: 20 },
  modal: { background: "#fff", border: "1px solid var(--border2)", borderRadius: 22, width: "100%", maxWidth: 560, padding: 36, position: "relative" as const, maxHeight: "92vh", overflowY: "auto" as const },
  modalX: { position: "absolute" as const, top: 20, right: 20, background: "var(--surface2)", border: "1px solid var(--border)", color: "var(--muted)", borderRadius: 8, width: 32, height: 32, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14 },
  field: { marginBottom: 18 },
  fieldLabel: { display: "block", fontSize: 11, fontWeight: 700, letterSpacing: "0.06em", textTransform: "uppercase" as const, color: "var(--subtle)", marginBottom: 7 },
  fieldInput: { fontFamily: "DM Sans, sans-serif", fontSize: 14, color: "var(--text)", background: "var(--surface)", border: "1px solid var(--border2)", borderRadius: 10, width: "100%", padding: "12px 14px", outline: "none" },
  btnPink: { fontFamily: "DM Sans, sans-serif", fontSize: 15, fontWeight: 700, width: "100%", padding: 15, background: "var(--pink)", color: "#fff", border: "none", borderRadius: 12, marginBottom: 10, boxShadow: "0 4px 20px rgba(255,45,120,0.25)" },
  btnSec: { fontFamily: "DM Sans, sans-serif", fontSize: 13, fontWeight: 500, width: "100%", padding: 12, background: "transparent", color: "var(--muted)", border: "1px solid var(--border2)", borderRadius: 12 },
  imgDrop: { border: "2px dashed var(--border2)", borderRadius: 12, padding: 20, textAlign: "center" as const, cursor: "pointer", background: "var(--surface)" },
};
